name: Unscramble GameViewModelTest

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: unit4/Unscramble
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin # See 'Supported distributions' for available options
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Run GameViewModelTest
        run: ./gradlew :app:testDebugUnitTest --tests "com.example.unscramble.ui.test.GameViewModelTest"
